apiVersion: v1
kind: Secret
metadata:
  name: nginx-basic-auth
  namespace: default
type: Opaque
stringData:
  auth: ENC[AES256_GCM,data:uwiMcAaqWvKKLyaNCqnu3AbwQoeYcr40Y0uPmA9925Gw39r8mBlWE8z+dmDOGX1I,iv:rMY2R6WWgJzEScxMSQF+i3Ikx6hnVvEOSbkNOAcNuLM=,tag:jgdaeun0JM3I+3OS3g/JMA==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2dGcEQ5MktudWovbkhP
        SXpEQlN0ZXNJaWNNZkpCTUN0MjR3QnlHOWhVCnlOVUF2TDc1bm1WUVpMYkN2cGxC
        NEEvbVZiWWFwY0VGSURNazFvMVF5cFEKLS0tIHUweXlEeXYxZGtFZTdVN2p4NWY5
        OUVMRWxEYml6K05odHo3S0NHRUVaYWcKD2yxNBhPXqtBgBgQ3TpmdNE4db6MVs36
        HU+clNDRb/5+FkP18HbKgzYJ8ta2t0EoIdzXW9eKKbc1qGxyh/3kzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T20:00:20Z"
  mac: ENC[AES256_GCM,data:l0b6Xs1JggHTurmt9qFbB1ZUWm1LlTptnBm+9ltKAIJDBAZ3ferywLnBu86RLDjFxLWhmURnCfIbwJd7Smj7n/IUQxT9i0zDzRvWvrYdTENVaO2jf68xTCTq2SzgaTi5quAeDfzAYJjFfD5SaxrqNlroGf8NdXrAuhP/MupoHgc=,iv:SZI7MXZwsO7W25KP5DruM3f5geHAYkEZL9yQafG2Vpw=,tag:bbvTn/bx361Hhp/Q5IxOew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
