apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/apps/demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
